import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.about': 'About Us',
    'nav.contact': 'Contact Us',
    'nav.locateUs': 'Locate Us',
    'nav.bookPickup': 'Book Pickup',
    'nav.bookPickupNow': 'Book Pickup Now',
    
    // Hero
    'hero.badge': 'RELIABLE LOGISTICS',
    'hero.title': 'Fast & Secure Delivery Services',
    'hero.subtitle': 'Your trusted partner for shipping across Kannauj and beyond. We pick up from your doorstep so you can relax.',
    'hero.bookNow': 'Book a Pickup Now',
    'hero.trackShipment': 'Track Your Shipment',
    'hero.trackSub': 'Already booked? Enter your tracking number to get live status updates.',
    'hero.placeholder': 'Enter tracking AWB...',
    'hero.track': 'Track',

    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'Comprehensive logistics solutions built for every type of shipment. From a single bottle of attar to a truckload of cargo.',
    'services.s1.title': 'Perfume & Attar Cargo',
    'services.s1.tag': 'Most Popular',
    'services.s1.desc': 'Specialized shipping for liquid perfumes, attars, and essential oils from Kannauj. Leak-proof, spill-safe packing with temperature-conscious handling.',
    'services.s1.f1': 'Leak-proof inner packing',
    'services.s1.f2': 'Bubble wrap + foam cushioning',
    'services.s1.f3': 'Flammable goods compliance',
    'services.s1.f4': 'Pan-India delivery',
    'services.s1.f5': 'Real-time tracking',
    'services.s2.title': 'Express Parcel Delivery',
    'services.s2.tag': 'Fast',
    'services.s2.desc': 'Door-to-door parcel delivery across 500+ Indian cities. Ideal for small to medium-sized boxes with 2–3 day guaranteed delivery.',
    'services.s2.f1': 'Same-day pickup',
    'services.s2.f2': '2–3 day delivery',
    'services.s2.f3': 'SMS + tracking updates',
    'services.s2.f4': 'Door delivery',
    'services.s2.f5': 'Up to 30 kg',
    'services.s3.title': 'E-Commerce Parcel Service',
    'services.s3.tag': 'Best for Sellers',
    'services.s3.desc': 'E-commerce shipping with monthly billing and free doorstep pickup. Minimum rates start at just ₹60 for up to 500g.',
    'services.s3.f1': 'Free doorstep pickup',
    'services.s3.f2': 'Monthly billing options',
    'services.s3.f3': 'Rates start from ₹60 (up to 500g)',
    'services.s3.f4': 'Secure Cash on Delivery (COD)',
    'services.s3.f5': 'Real-time tracking & reports',
    'services.s4.title': 'Cargo & Bulk Shipping',
    'services.s4.tag': 'Heavy Load',
    'services.s4.desc': 'For large industrial and commercial shipments — full-truck or part-load cargo from Kannauj to any warehouse or factory in India.',
    'services.s4.f1': 'FTL & LTL options',
    'services.s4.f2': 'Pallet and crate handling',
    'services.s4.f3': 'Commercial invoicing',
    'services.s4.f4': '3–5 day delivery',
    'services.s4.f5': '100+ kg capacity',
    'services.s5.title': 'Document & Envelope Courier',
    'services.s5.tag': 'Lightweight',
    'services.s5.desc': 'Legal documents, business papers, certificates, and envelopes sent safely with next-day delivery to major cities.',
    'services.s5.f1': 'Next-day city delivery',
    'services.s5.f2': 'Tamper-proof envelope',
    'services.s5.f3': 'Proof of delivery',
    'services.s5.f4': 'Up to 500 grams',
    'services.s5.f5': 'Signature on receipt',
    'services.s6.title': 'Pan-India B2B Logistics',
    'services.s6.tag': 'Business',
    'services.s6.desc': 'Volume shipping contracts for businesses. Dedicated account manager, weekly billing, and priority pickup slots.',
    'services.s6.f1': 'Dedicated account manager',
    'services.s6.f2': 'Monthly billing',
    'services.s6.f3': 'Priority pickup slots',
    'services.s6.f4': 'Custom SLAs',
    'services.s6.f5': 'API integration available',
    'services.startingAt': 'Starting at',
    'services.bookNow': 'Book Now',
    'services.network.subtitle': 'Our Delivery Network',
    'services.network.title': "Powered by India's Best",
    'services.network.desc': "We work with top carriers to guarantee fast, reliable delivery across 19,500+ pin codes in India. We auto-select the best carrier for every shipment based on speed, cost & destination.",
    'services.locateUs.tag': "Branch Locator",
    'services.locateUs.title': "Find Nearest DTDC & Partner Offices",
    'services.locateUs.desc': "Easily locate official collection centers, branch offices, and partner delivery hubs near your area.",
    'services.locateUs.btn': "Locate Us Now",

    // Specialized Industry
    'industry.badge': 'Perfume Capital Experts',
    'industry.title': 'Specialized Handling for the Fragrance Industry',
    'industry.desc': 'Born in Kannauj, we understand the delicate nature of attars, essential oils, and perfumes. Our specialized shock-proof packaging and careful handling ensure your precious cargo reaches perfectly intact.',
    'industry.feature1': 'Leak-proof Packing',
    'industry.feature2': 'Spill-safe Logistics',
    'industry.feature3': 'Same-day Kannauj Pickup',
    'industry.feature4': 'Real-time Tracking',
    'industry.consult': 'Consult an Expert',
    'industry.serve': 'We proudly serve:',
    'industry.list1': 'Perfume Manufacturers',
    'industry.list2': 'Attar Producers & Exporters',
    'industry.list3': 'Essential Oil Suppliers',
    'industry.list4': 'Aroma Chemical Dealers',
    'industry.list5': 'Glass Bottle & Packaging Suppliers',
    'industry.list6': 'Cosmetic Businesses',
    'industry.list7': 'Gift Item Distributors',

    // Rate Estimator
    'rate.cost.title': 'How Much Will It Cost?',
    'rate.cost.desc': 'Get an instant estimate — no registration needed. Provide basic details and our team will share the best possible rates instantly via WhatsApp.',
    'rate.cost.b1': 'No hidden charges',
    'rate.cost.b2': 'Best B2B rates guaranteed',
    'rate.title': 'Instant Rate Estimator',
    'rate.weight.label': 'Parcel Weight (Approx)',
    'rate.weight.ph': 'e.g. 5',
    'rate.pincode.label': 'Destination Pincode',
    'rate.pincode.ph': 'e.g. 110001',
    'rate.btn': 'Get Rate via WhatsApp',

    // About
    'about.mission': 'Our Mission',
    'about.title': 'Delivering More Than Just Parcels',
    'about.p1': "PICKUPWALE was founded with a single purpose: to give India's fragrance businesses — the perfumers, attar makers, and traders of Kannauj — a logistics partner who truly understands their needs.",
    'about.p2': "Perfume and attar aren't just products. They carry years of craft, precious ingredients, and a family's livelihood. We treat every shipment like it's our own, with the care and urgency it deserves.",
    'about.stat1.val': '14+',
    'about.stat1.label': 'Years of Growing Together',
    'about.stat2.val': '10k+',
    'about.stat2.label': 'Happy Customers',
    'about.values.title': 'Our Core Values',
    'about.v1.title': 'Customer First',
    'about.v1.desc': 'Dedicated support in Hindi & English, always ready to help you track and manage shipments.',
    'about.v2.title': 'On-Time Delivery',
    'about.v2.desc': 'We understand business deadlines. Fast transit times is our top priority.',
    'about.v3.title': 'The People Behind It',
    'about.v3.desc': 'A dedicated team of logistics experts managing your parcels day and night.',

    // Contact
    'contact.badge': 'Contact Us / DTDC Kannauj',
    'contact.title': 'Get in Touch',
    'contact.subtitle': "Have a question or need a pickup? We're here to help — reach out anytime.",
    'contact.office.title': 'DTDC Couriers Kannauj (Main Office)',
    'contact.office.map': 'View on Map',
    'contact.call.title': 'Call Us',
    'contact.call.desc': 'Mon – Sat, 9 am – 7 pm',
    'contact.wa.title': 'WhatsApp',
    'contact.wa.desc': 'Quick replies on WhatsApp',
    'contact.email.title': 'Email',
    'contact.email.desc': 'We reply within 24 hours',
    'contact.hours.title': 'Working Hours',
    'contact.hours.d1': 'Mon – Sat: 9:00 AM – 7:00 PM',
    'contact.hours.d2': 'Sunday: Closed',
    'contact.form.title': 'Send Us a Message',
    'contact.form.name': 'Your Name',
    'contact.form.nameph': 'e.g. Rajat Kumar',
    'contact.form.phone': 'Phone Number',
    'contact.form.phoneph': 'e.g. 98XXXXXXXX',
    'contact.form.subject': 'Subject',
    'contact.form.subph': 'e.g. Booking / Tracking / General Enquiry',
    'contact.form.message': 'Message',
    'contact.form.msgph': 'Tell us how we can help you...',
    'contact.form.btn': 'Send via WhatsApp',

    // WhatsApp Widget
    'wa.tooltip': 'Need help? Chat with us!',

    // Footer
    'footer.desc': "India's Trusted Courier & Cargo Partner. Fast, safe, and reliable delivery across India, specializing in the fragrance industry.",
    'footer.quickLinks': 'Useful Links',
    'footer.services': 'Services',
    'footer.contact': 'Contact Us',
    'footer.rights': '© 2024 Pickupwale. All rights reserved.',
    'footer.s1': 'Free Doorstep Pickup',
    'footer.s2': 'All India Courier',
    'footer.s3': 'Surface Cargo',
    'footer.s4': 'Fragile & Perfume Handling',
    'footer.s5': 'B2B Logistics',
    'footer.s6': 'eCommerce & COD',
    'footer.l1': 'Home',
    'footer.l2': 'About Us',
    'footer.l3': 'Delivery Network',
    'footer.l4': 'Book a Pickup',
    'footer.l5': 'Get Rates',
    'footer.l6': 'Locate Us',
    'footer.wa': 'WhatsApp Us',
    'footer.keywords': 'SEO Keywords: Pickupwale, Courier Service Kannauj, Cargo Service Kannauj, Perfume Courier, Fragrance Logistics, B2B Courier India.',
  },
  hi: {
    // Navbar
    'nav.home': 'होम',
    'nav.services': 'सुविधाएं',
    'nav.about': 'हमारे बारे में',
    'nav.contact': 'संपर्क करें',
    'nav.locateUs': 'शाखा खोजें (Locate Us)',
    'nav.bookPickup': 'पिकअप बुक करें',
    'nav.bookPickupNow': 'अभी पिकअप बुक करें',
    
    // Hero
    'hero.badge': 'भरोसेमंद रसद (लॉजिस्टिक्स)',
    'hero.title': 'तेज़ और सुरक्षित कूरियर सुविधाएं',
    'hero.subtitle': 'कन्नौज और पूरे भारत में शिपिंग के लिए आपका भरोसेमंद साथी। हम आपके दरवाजे से पिकअप करते हैं ताकि आप आराम कर सकें।',
    'hero.bookNow': 'अभी पिकअप बुक करें',
    'hero.trackShipment': 'अपना पार्सल ट्रैक करें',
    'hero.trackSub': 'क्या आपने पहले ही बुकिंग कर ली है? लाइव स्टेटस अपडेट के लिए अपना ट्रैकिंग नंबर डालें।',
    'hero.placeholder': 'AWB ट्रैकिंग नंबर डालें...',
    'hero.track': 'ट्रैक करें',

    // Services
    'services.title': 'हमारी सुविधाएं',
    'services.subtitle': 'हर प्रकार के शिपमेंट के लिए संपूर्ण लॉजिस्टिक्स समाधान। इत्र की एक बोतल से लेकर ट्रक-भर कार्गो तक।',
    'services.s1.title': 'इत्र और अत्तर कार्गो',
    'services.s1.tag': 'सबसे लोकप्रिय',
    'services.s1.desc': 'कन्नौज से तरल इत्र, अत्तर और आवश्यक तेलों की विशेष शिपिंग। सुरक्षित और फैलने से रोकने वाली पैकिंग।',
    'services.s1.f1': 'रिसाव-प्रूफ अंदरूनी पैकिंग',
    'services.s1.f2': 'बबल रैप + फोम कुशनिंग',
    'services.s1.f3': 'ज्वलनशील वस्तु अनुपालन',
    'services.s1.f4': 'पैन-इंडिया डिलीवरी',
    'services.s1.f5': 'रियल-टाइम ट्रैकिंग',
    'services.s2.title': 'एक्सप्रेस पार्सल डिलीवरी',
    'services.s2.tag': 'तेज़',
    'services.s2.desc': 'भारत के 500 से अधिक शहरों में डोर-टू-डोर पार्सल डिलीवरी। 2-3 दिन की गारंटीकृत डिलीवरी।',
    'services.s2.f1': 'एक ही दिन में पिकअप',
    'services.s2.f2': '2-3 दिन में डिलीवरी',
    'services.s2.f3': 'SMS + ट्रैकिंग अपडेट',
    'services.s2.f4': 'डोर डिलीवरी',
    'services.s2.f5': '30 किलो तक',
    'services.s3.title': 'ई-कॉमर्स पार्सल सर्विस',
    'services.s3.tag': 'विक्रेताओं के लिए',
    'services.s3.desc': 'मासिक बिलिंग और मुफ्त डोरस्टेप पिकअप के साथ ई-कॉमर्स शिपिंग। न्यूनतम दरें 500 ग्राम तक के लिए केवल ₹60 से शुरू होती हैं।',
    'services.s3.f1': 'फ्री डोरस्टेप पिकअप',
    'services.s3.f2': 'मासिक बिलिंग विकल्प (Monthly Billing)',
    'services.s3.f3': 'दरें ₹60 से शुरू (500 ग्राम तक)',
    'services.s3.f4': 'सुरक्षित कैश ऑन डिलीवरी (COD)',
    'services.s3.f5': 'रियल-टाइम ट्रैकिंग और रिपोर्ट',
    'services.s4.title': 'कार्गो और थोक शिपिंग',
    'services.s4.tag': 'भारी भार',
    'services.s4.desc': 'बड़े औद्योगिक और वाणिज्यिक शिपमेंट के लिए — कन्नौज से भारत के किसी भी गोदाम या कारखाने तक पार्सल।',
    'services.s4.f1': 'FTL और LTL विकल्प',
    'services.s4.f2': 'पैलेट और क्रेट हैंडलिंग',
    'services.s4.f3': 'वाणिज्यिक चालान',
    'services.s4.f4': '3-5 दिन में डिलीवरी',
    'services.s4.f5': '100+ किलो क्षमता',
    'services.s5.title': 'दस्तावेज़ और लिफाफा कूरियर',
    'services.s5.tag': 'हल्का भार',
    'services.s5.desc': 'कानूनी दस्तावेज़, व्यापारिक दस्तावेज़, प्रमाणपत्र और लिफाफे बड़े शहरों में अगले दिन की डिलीवरी के साथ सुरक्षित भेजना।',
    'services.s5.f1': 'अगले दिन डिलीवरी',
    'services.s5.f2': 'छेड़छाड़-प्रूफ लिफाफा',
    'services.s5.f3': 'डिलीवरी का प्रमाण',
    'services.s5.f4': '500 ग्राम तक',
    'services.s5.f5': 'प्राप्ति पर हस्ताक्षर',
    'services.s6.title': 'पैन-इंडिया B2B लॉजिस्टिक्स',
    'services.s6.tag': 'व्यापार',
    'services.s6.desc': 'व्यापार के लिए वॉल्यूम शिपिंग कॉन्ट्रैक्ट। समर्पित खाता प्रबंधक, साप्ताहिक बिलिंग और प्राथमिकता पिकअप।',
    'services.s6.f1': 'समर्पित खाता प्रबंधक',
    'services.s6.f2': 'मासिक बिलिंग',
    'services.s6.f3': 'प्राथमिकता पिकअप स्लॉट',
    'services.s6.f4': 'कस्टम SLA',
    'services.s6.f5': 'API एकीकरण उपलब्ध',
    'services.startingAt': 'शुरुआती कीमत',
    'services.bookNow': 'बुक करें',
    'services.network.subtitle': 'हमारा डिलीवरी नेटवर्क',
    'services.network.title': "भारत के सर्वश्रेष्ठ द्वारा संचालित",
    'services.network.desc': "हम भारत में 19,500+ पिन कोड में तेज़, विश्वसनीय डिलीवरी की गारंटी के लिए शीर्ष कंपनियों के साथ काम करते हैं। हम गति, लागत और गंतव्य के आधार पर प्रत्येक शिपमेंट के लिए सबसे अच्छा वाहक चुनते हैं।",
    'services.locateUs.tag': "शाखा खोजें",
    'services.locateUs.title': "अपने नजदीकी DTDC और पार्टनर कार्यालय खोजें",
    'services.locateUs.desc': "अपने क्षेत्र के पास आधिकारिक संग्रह केंद्रों, शाखा कार्यालयों और पार्टनर डिलीवरी हब का आसानी से पता लगाएं।",
    'services.locateUs.btn': "अभी शाखा खोजें (Locate Us)",

    // Specialized Industry
    'industry.badge': 'इत्र नगरी के विशेषज्ञ',
    'industry.title': 'सुगंध उद्योग के लिए विशेष पैकिंग और डिलीवरी',
    'industry.desc': 'कन्नौज के निवासी होने के नाते, हम अत्तर, आवश्यक तेलों और इत्र की नाज़ुक प्रकृति को समझते हैं। हमारी विशेष शॉक-प्रूफ पैकेजिंग और सावधानीपूर्वक हैंडलिंग यह सुनिश्चित करती है कि आपका कीमती सामान बिल्कुल सुरक्षित पहुंचे।',
    'industry.feature1': 'लीक-प्रूफ पैकिंग',
    'industry.feature2': 'सुरक्षित रसद (लॉजिस्टिक्स)',
    'industry.feature3': 'उसी दिन कन्नौज से पिकअप',
    'industry.feature4': 'रियल-टाइम ट्रैकिंग',
    'industry.consult': 'विशेषज्ञ से सलाह लें',
    'industry.serve': 'हम गर्व से सेवा करते हैं:',
    'industry.list1': 'इत्र (Perfume) निर्माता',
    'industry.list2': 'अत्तर निर्माता और निर्यातक',
    'industry.list3': 'आवश्यक तेल (Essential Oil) आपूर्तिकर्ता',
    'industry.list4': 'अरोमा केमिकल डीलर',
    'industry.list5': 'कांच की बोतल और पैकेजिंग आपूर्तिकर्ता',
    'industry.list6': 'कॉस्मेटिक व्यवसाय',
    'industry.list7': 'गिफ्ट आइटम वितरक',

    // Rate Estimator
    'rate.cost.title': 'कितना खर्च आएगा?',
    'rate.cost.desc': 'तुरंत अनुमान प्राप्त करें — किसी पंजीकरण की आवश्यकता नहीं है। मूल विवरण प्रदान करें और हमारी टीम WhatsApp के माध्यम से सर्वोत्तम संभव दरें तुरंत साझा करेगी।',
    'rate.cost.b1': 'कोई छिपा हुआ शुल्क नहीं',
    'rate.cost.b2': 'सर्वोत्तम B2B दरों की गारंटी',
    'rate.title': 'तत्काल दर अनुमान (Rate Estimator)',
    'rate.weight.label': 'पार्सल का वजन (लगभग)',
    'rate.weight.ph': 'उदा. 5',
    'rate.pincode.label': 'गंतव्य पिनकोड (Destination Pincode)',
    'rate.pincode.ph': 'उदा. 110001',
    'rate.btn': 'WhatsApp पर दर प्राप्त करें',

    // About
    'about.mission': 'हमारा लक्ष्य',
    'about.title': 'सिर्फ पार्सल ही नहीं, उससे भी बढ़कर डिलीवरी',
    'about.p1': "PICKUPWALE की स्थापना एक ही उद्देश्य से की गई थी: भारत के सुगंध व्यवसायों—कन्नौज के इत्र निर्माताओं, अत्तर बनाने वालों और व्यापारियों—को एक ऐसा लॉजिस्टिक्स पार्टनर देना जो उनकी जरूरतों को सच में समझता हो।",
    'about.p2': "इत्र और अत्तर सिर्फ उत्पाद नहीं हैं। उनके साथ वर्षों का शिल्प, कीमती सामग्रियां और एक परिवार की आजीविका जुड़ी होती है। हम हर शिपमेंट को अपना मानकर पूरी सावधानी और तत्परता के साथ संभालते हैं।",
    'about.stat1.val': '14+',
    'about.stat1.label': 'सालों से साथ बढ़ रहे हैं',
    'about.stat2.val': '10k+',
    'about.stat2.label': 'संतुष्ट ग्राहक',
    'about.values.title': 'हमारे मुख्य मूल्य',
    'about.v1.title': 'ग्राहक सर्वोपरि (सबसे ऊपर)',
    'about.v1.desc': 'हिंदी और अंग्रेजी में समर्पित सहायता, आपके शिपमेंट को ट्रैक और प्रबंधित करने में मदद के लिए हमेशा तैयार।',
    'about.v2.title': 'समय पर डिलीवरी',
    'about.v2.desc': 'हम व्यापार की समय-सीमा समझते हैं। तेज़ और सुरक्षित पारगमन हमारा मुख्य लक्ष्य है।',
    'about.v3.title': 'इसके पीछे के लोग',
    'about.v3.desc': 'लॉजिस्टिक्स विशेषज्ञों की एक समर्पित टीम जो दिन-रात आपके पार्सल का प्रबंधन करती है।',

    // Contact
    'contact.badge': 'संपर्क करें / DTDC कन्नौज',
    'contact.title': 'हमसे जुड़ें',
    'contact.subtitle': "कोई सवाल है या पिकअप चाहिए? हम मदद के लिए यहाँ हैं — कभी भी संपर्क करें।",
    'contact.office.title': 'DTDC कूरियर कन्नौज (मुख्य कार्यालय)',
    'contact.office.map': 'मैप पर देखें',
    'contact.call.title': 'हमें कॉल करें',
    'contact.call.desc': 'सोम - शनि, सुबह 9 - शाम 7 बजे',
    'contact.wa.title': 'WhatsApp',
    'contact.wa.desc': 'WhatsApp पर त्वरित (Quick) उत्तर',
    'contact.email.title': 'ईमेल',
    'contact.email.desc': 'हम 24 घंटे के भीतर जवाब देते हैं',
    'contact.hours.title': 'कार्य का समय',
    'contact.hours.d1': 'सोम - शनि: सुबह 9:00 - शाम 7:00 बजे',
    'contact.hours.d2': 'रविवार: छुट्टी (Closed)',
    'contact.form.title': 'हमें एक संदेश (Message) भेजें',
    'contact.form.name': 'आपका नाम',
    'contact.form.nameph': 'उदा. रजत कुमार',
    'contact.form.phone': 'फ़ोन नंबर',
    'contact.form.phoneph': 'उदा. 98XXXXXXXX',
    'contact.form.subject': 'विषय (Subject)',
    'contact.form.subph': 'उदा. बुकिंग / ट्रैकिंग / सामान्य पूछताछ',
    'contact.form.message': 'संदेश (Message)',
    'contact.form.msgph': 'बताइए हम आपकी कैसे मदद कर सकते हैं...',
    'contact.form.btn': 'WhatsApp के माध्यम से भेजें',

    // WhatsApp Widget
    'wa.tooltip': 'मदद चाहिए? हमसे चैट करें!',
    
    // Footer
    'footer.desc': "भारत का भरोसेमंद कूरियर और कार्गो पार्टनर। पूरे देश में तेज़, सुरक्षित और भरोसेमंद डिलीवरी, विशेष रूप से सुगंध उद्योग के लिए।",
    'footer.quickLinks': 'त्वरित लिंक (Quick Links)',
    'footer.services': 'सुविधाएं (Services)',
    'footer.contact': 'संपर्क करें (Contact)',
    'footer.rights': 'सर्वाधिकार सुरक्षित।',
    'footer.s1': 'फ्री डोरस्टेप पिकअप',
    'footer.s2': 'पैन इंडिया कूरियर',
    'footer.s3': 'सर्फेस कार्गो',
    'footer.s4': 'नाज़ुक और इत्र हैंडलिंग',
    'footer.s5': 'B2B लॉजिस्टिक्स',
    'footer.s6': 'ई-कॉमर्स और COD',
    'footer.l1': 'होम',
    'footer.l2': 'हमारे बारे में',
    'footer.l3': 'डिलीवरी नेटवर्क',
    'footer.l4': 'पिकअप बुक करें',
    'footer.l5': 'किराया पता करें',
    'footer.l6': 'शाखा खोजें (Locate Us)',
    'footer.wa': 'WhatsApp मैसेज भेजें',
    'footer.keywords': 'SEO Keywords: Pickupwale, Courier Service Kannauj, Cargo Service Kannauj, Perfume Courier, Fragrance Logistics, B2B Courier India.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'hi' : 'en'));
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
